# NBBinder configuration file for the notebooks in 
# the repository github/rmsrosa/modelagem_matematica

version: 0.12a

path_to_notes: .

contents:
  toc_nb_name: 00.00-Pagina_Inicial.ipynb
  toc_title: Sumário
  show_index_in_toc: True

header: "[*Guia de aulas da disciplina de Modelagem Matemática*](https://github.com/rmsrosa/modelagem_matematica) *do* [*IM-UFRJ*](https://www.im.ufrj.br)."

navigators:
  core_navigators:
    - 00.00-Pagina_Inicial.ipynb
  show_nb_title_in_nav: True
  show_index_in_nav: False

badges:
  - alt: Google Colab
    title: Open in Google Colab
    url: https://colab.research.google.com/github/rmsrosa/modelagem_matematica/blob/master/aulas
    src: https://colab.research.google.com/assets/colab-badge.svg
  - alt: Binder
    title: Open in binder
    url: https://mybinder.org/v2/gh/rmsrosa/modelagem_matematica/master?filepath=aulas
    src: https://mybinder.org/badge.svg
  - alt: nbviewer
    title: View in NBViewer
    url: https://nbviewer.jupyter.org/github/rmsrosa/modelagem_matematica/blob/master/aulas
    label: view in
    message: nbviewer
    color: orange
  - alt: slides
    title: View Slides
    url: https://nbviewer.jupyter.org/github/rmsrosa/modelagem_matematica/blob/master/aulas/slides
    extension: .slides.html
    label: view
    message: slides
    color: darkgreen

exports:
  - export_path: slides
    exporter_name: slides
    exporter_args:
      reveal_scroll: True
