makebook:
  toc_nb_name : '00.00-Indice.ipynb'
  book_header : "*[Notas de aula da disciplina de Modelagem Matemática](https://github.com/rmsrosa/modelagem_matematica) do [IM-UFRJ](https://www.im.ufrj.br).*"
  center_nav : 
    - '00.00-Indice.ipynb'
    - 'BA.00-Bibliografia.ipynb'
  directory : '../notebooks'
  repository : 'rmsrosa/modelagem_matematica'
  branch : 'master'
  show_colab : True
  show_binder : True
  show_full_entry : True